CREATE TABLE `drug_interaction_checks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`performed_by` int,
	`medications_checked` text NOT NULL,
	`conditions_considered` text,
	`interactions_found` int NOT NULL DEFAULT 0,
	`highest_severity` enum('none','minor','moderate','major','contraindicated') NOT NULL DEFAULT 'none',
	`overall_risk` enum('low','moderate','high') NOT NULL DEFAULT 'low',
	`full_results` text NOT NULL,
	`action_taken` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `drug_interaction_checks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `medical_conditions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patient_id` int NOT NULL,
	`condition_name` varchar(255) NOT NULL,
	`condition_code` varchar(50),
	`condition_type` enum('chronic_disease','allergy','contraindication','risk_factor','past_condition') NOT NULL,
	`severity` enum('mild','moderate','severe') DEFAULT 'moderate',
	`status` enum('active','resolved','in_remission') NOT NULL DEFAULT 'active',
	`diagnosed_date` date,
	`resolved_date` date,
	`diagnosed_by` int,
	`notes` text,
	`affects_medications` boolean NOT NULL DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `medical_conditions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `medicine_images` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`image_url` varchar(500) NOT NULL,
	`image_key` varchar(500) NOT NULL,
	`thumbnail_url` varchar(500),
	`file_size` int,
	`mime_type` varchar(50),
	`width` int,
	`height` int,
	`identification_status` enum('pending','identified','failed','manual_review') NOT NULL DEFAULT 'pending',
	`identified_drug_name` varchar(255),
	`identified_generic_name` varchar(255),
	`identified_brand_name` varchar(255),
	`identified_dosage` varchar(100),
	`identification_confidence` decimal(5,2),
	`verified_by_user` boolean NOT NULL DEFAULT false,
	`verified_by_clinician` boolean NOT NULL DEFAULT false,
	`verified_by` int,
	`extracted_text` text,
	`processing_attempts` int NOT NULL DEFAULT 0,
	`last_processed_at` timestamp,
	`error_message` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `medicine_images_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `patient_medications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patient_id` int NOT NULL,
	`drug_name` varchar(255) NOT NULL,
	`generic_name` varchar(255),
	`brand_name` varchar(255),
	`dosage` varchar(100),
	`frequency` varchar(100),
	`route` varchar(50),
	`start_date` timestamp NOT NULL DEFAULT (now()),
	`end_date` timestamp,
	`is_active` boolean NOT NULL DEFAULT true,
	`prescribed_by` int,
	`prescription_id` int,
	`source` enum('prescription','otc','self_reported') NOT NULL DEFAULT 'self_reported',
	`identified_from_image` boolean NOT NULL DEFAULT false,
	`medicine_image_id` int,
	`purpose` text,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `patient_medications_id` PRIMARY KEY(`id`)
);
