CREATE TABLE `soap_export_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`export_id` varchar(64) NOT NULL,
	`patient_id` int NOT NULL,
	`clinician_id` int NOT NULL,
	`encounter_date` timestamp NOT NULL,
	`soap_content` text NOT NULL,
	`export_format` enum('pdf_with_qr','pdf_simple','hl7_v2','hl7_v3','fhir_json','fhir_xml') NOT NULL,
	`file_key` varchar(512),
	`file_url` varchar(1024),
	`file_size` int,
	`qr_code_data` text,
	`qr_code_image_key` varchar(512),
	`hl7_message_type` varchar(50),
	`hl7_version` varchar(20),
	`hl7_message_id` varchar(255),
	`destination_system` varchar(255),
	`destination_facility_id` varchar(100),
	`status` enum('pending','generated','delivered','failed','expired') NOT NULL DEFAULT 'pending',
	`error_message` text,
	`exported_by` int NOT NULL,
	`export_purpose` varchar(255),
	`accessed_count` int NOT NULL DEFAULT 0,
	`last_accessed_at` timestamp,
	`expires_at` timestamp,
	`verification_code` varchar(64),
	`checksum_md5` varchar(32),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `soap_export_logs_id` PRIMARY KEY(`id`),
	CONSTRAINT `soap_export_logs_export_id_unique` UNIQUE(`export_id`)
);
--> statement-breakpoint
CREATE TABLE `soap_note_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`name_ar` varchar(255) NOT NULL,
	`category` enum('chest_pain','fever','trauma','pediatric','respiratory','gastrointestinal','neurological','general') NOT NULL,
	`subjective_template` text NOT NULL,
	`objective_template` text NOT NULL,
	`assessment_template` text NOT NULL,
	`plan_template` text NOT NULL,
	`description` text NOT NULL,
	`description_ar` text NOT NULL,
	`keywords` text,
	`keywords_ar` text,
	`common_symptoms` text,
	`red_flags` text,
	`typical_diagnoses` text,
	`usage_count` int NOT NULL DEFAULT 0,
	`last_used` timestamp,
	`is_active` boolean NOT NULL DEFAULT true,
	`is_system_template` boolean NOT NULL DEFAULT true,
	`created_by` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `soap_note_templates_id` PRIMARY KEY(`id`)
);
