CREATE TABLE `appointments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patient_id` int NOT NULL,
	`facility_id` int,
	`facility_name` varchar(255),
	`facility_address` text,
	`clinician_id` int,
	`appointment_date` timestamp NOT NULL,
	`duration` int DEFAULT 30,
	`appointment_type` enum('consultation','follow_up','emergency','screening','vaccination','other') NOT NULL DEFAULT 'consultation',
	`status` enum('pending','confirmed','completed','cancelled','no_show') NOT NULL DEFAULT 'pending',
	`chief_complaint` text,
	`notes` text,
	`reminder_sent` boolean DEFAULT false,
	`reminder_sent_at` timestamp,
	`cancelled_by` int,
	`cancellation_reason` text,
	`cancelled_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `appointments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `medication_adherence` (
	`id` int AUTO_INCREMENT NOT NULL,
	`prescription_id` int NOT NULL,
	`patient_id` int NOT NULL,
	`scheduled_time` timestamp NOT NULL,
	`taken` boolean DEFAULT false,
	`taken_at` timestamp,
	`missed` boolean DEFAULT false,
	`missed_reason` text,
	`reminder_sent` boolean DEFAULT false,
	`reminder_sent_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `medication_adherence_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `messages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sender_id` int NOT NULL,
	`recipient_id` int NOT NULL,
	`subject` varchar(255),
	`content` text NOT NULL,
	`encrypted` boolean DEFAULT true,
	`read` boolean DEFAULT false,
	`read_at` timestamp,
	`thread_id` int,
	`reply_to_id` int,
	`case_id` int,
	`attachments` text,
	`deleted_by_sender` boolean DEFAULT false,
	`deleted_by_recipient` boolean DEFAULT false,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `messages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `prescriptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patient_id` int NOT NULL,
	`case_id` int,
	`clinician_id` int NOT NULL,
	`medication_name` varchar(255) NOT NULL,
	`generic_name` varchar(255),
	`dosage` varchar(100) NOT NULL,
	`frequency` varchar(100) NOT NULL,
	`route` varchar(50),
	`start_date` timestamp NOT NULL,
	`end_date` timestamp,
	`duration` int,
	`instructions` text,
	`warnings` text,
	`status` enum('active','completed','discontinued','on_hold') NOT NULL DEFAULT 'active',
	`refills_allowed` int DEFAULT 0,
	`refills_remaining` int DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `prescriptions_id` PRIMARY KEY(`id`)
);
