CREATE TABLE `fhir_conditions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fhir_id` varchar(64) NOT NULL,
	`resource_type` varchar(50) NOT NULL DEFAULT 'Condition',
	`patient_fhir_id` varchar(64) NOT NULL,
	`clinical_status` varchar(50) NOT NULL,
	`verification_status` varchar(50),
	`category` text,
	`severity` varchar(50),
	`code` text NOT NULL,
	`body_site` text,
	`onset_date_time` timestamp,
	`onset_age` int,
	`onset_string` varchar(255),
	`abatement_date_time` timestamp,
	`abatement_age` int,
	`abatement_string` varchar(255),
	`recorded_date` timestamp,
	`recorder` varchar(255),
	`asserter` varchar(255),
	`stage` text,
	`evidence` text,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fhir_conditions_id` PRIMARY KEY(`id`),
	CONSTRAINT `fhir_conditions_fhir_id_unique` UNIQUE(`fhir_id`)
);
--> statement-breakpoint
CREATE TABLE `fhir_medication_statements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fhir_id` varchar(64) NOT NULL,
	`resource_type` varchar(50) NOT NULL DEFAULT 'MedicationStatement',
	`patient_fhir_id` varchar(64) NOT NULL,
	`status` varchar(50) NOT NULL,
	`medication_codeable_concept` text,
	`medication_reference` varchar(255),
	`effective_date_time` timestamp,
	`effective_period_start` timestamp,
	`effective_period_end` timestamp,
	`date_asserted` timestamp,
	`information_source` varchar(255),
	`derived_from` text,
	`reason_code` text,
	`reason_reference` text,
	`notes` text,
	`dosage` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fhir_medication_statements_id` PRIMARY KEY(`id`),
	CONSTRAINT `fhir_medication_statements_fhir_id_unique` UNIQUE(`fhir_id`)
);
--> statement-breakpoint
CREATE TABLE `fhir_observations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fhir_id` varchar(64) NOT NULL,
	`resource_type` varchar(50) NOT NULL DEFAULT 'Observation',
	`patient_fhir_id` varchar(64) NOT NULL,
	`status` varchar(50) NOT NULL,
	`category` text,
	`code` text NOT NULL,
	`effective_date_time` timestamp,
	`effective_period_start` timestamp,
	`effective_period_end` timestamp,
	`issued` timestamp,
	`performer` text,
	`value_quantity_value` decimal(10,2),
	`value_quantity_unit` varchar(50),
	`value_quantity_system` varchar(255),
	`value_quantity_code` varchar(50),
	`value_codeable_concept` text,
	`value_string` text,
	`value_boolean` boolean,
	`value_integer` int,
	`value_range` text,
	`value_ratio` text,
	`value_sampled_data` text,
	`value_time` time,
	`value_date_time` timestamp,
	`value_period` text,
	`data_absent_reason` text,
	`interpretation` text,
	`notes` text,
	`body_site` text,
	`method` text,
	`reference_range` text,
	`has_member` text,
	`derived_from` text,
	`component` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fhir_observations_id` PRIMARY KEY(`id`),
	CONSTRAINT `fhir_observations_fhir_id_unique` UNIQUE(`fhir_id`)
);
--> statement-breakpoint
CREATE TABLE `fhir_patients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fhir_id` varchar(64) NOT NULL,
	`resource_type` varchar(50) NOT NULL DEFAULT 'Patient',
	`user_id` int,
	`identifiers` text NOT NULL,
	`family_name` varchar(255),
	`given_names` text,
	`prefix` varchar(50),
	`suffix` varchar(50),
	`gender` enum('male','female','other','unknown'),
	`birth_date` date,
	`telecom` text,
	`addresses` text,
	`marital_status` varchar(50),
	`languages` text,
	`general_practitioner` text,
	`managing_organization` varchar(255),
	`active` boolean DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`last_updated` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fhir_patients_id` PRIMARY KEY(`id`),
	CONSTRAINT `fhir_patients_fhir_id_unique` UNIQUE(`fhir_id`)
);
