CREATE TABLE `consultations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patient_id` int NOT NULL,
	`clinician_id` int NOT NULL,
	`appointment_id` int,
	`scheduled_time` timestamp NOT NULL,
	`start_time` timestamp,
	`end_time` timestamp,
	`duration` int,
	`status` enum('scheduled','waiting','in_progress','completed','cancelled','no_show') NOT NULL DEFAULT 'scheduled',
	`room_id` varchar(100) NOT NULL,
	`chief_complaint` text,
	`notes` text,
	`diagnosis` text,
	`prescription_generated` boolean DEFAULT false,
	`recording_url` varchar(500),
	`recording_enabled` boolean DEFAULT false,
	`chat_transcript` text,
	`payment_status` enum('pending','paid','failed','refunded') DEFAULT 'pending',
	`amount` int,
	`patient_rating` int,
	`patient_feedback` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `consultations_id` PRIMARY KEY(`id`),
	CONSTRAINT `consultations_room_id_unique` UNIQUE(`room_id`)
);
