CREATE TABLE `doctor_patient_relationships` (
	`id` int AUTO_INCREMENT NOT NULL,
	`doctor_id` int NOT NULL,
	`patient_id` int NOT NULL,
	`relationship_type` enum('primary','specialist','consultant','referral') NOT NULL DEFAULT 'primary',
	`status` enum('active','inactive','pending','terminated') NOT NULL DEFAULT 'pending',
	`can_view_records` boolean DEFAULT true,
	`can_prescribe` boolean DEFAULT true,
	`can_message` boolean DEFAULT true,
	`can_schedule_appointments` boolean DEFAULT true,
	`notes` text,
	`referred_by` int,
	`established_at` timestamp NOT NULL DEFAULT (now()),
	`terminated_at` timestamp,
	`termination_reason` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `doctor_patient_relationships_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `patient_invitations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`doctor_id` int NOT NULL,
	`invitation_code` varchar(32) NOT NULL,
	`patient_email` varchar(320),
	`patient_phone` varchar(50),
	`patient_name` varchar(255),
	`status` enum('pending','accepted','expired','cancelled') NOT NULL DEFAULT 'pending',
	`accepted_by` int,
	`accepted_at` timestamp,
	`expires_at` timestamp NOT NULL,
	`personal_message` text,
	`sent_via` enum('email','sms','link','qr_code'),
	`times_viewed` int DEFAULT 0,
	`last_viewed_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `patient_invitations_id` PRIMARY KEY(`id`),
	CONSTRAINT `patient_invitations_invitation_code_unique` UNIQUE(`invitation_code`)
);
--> statement-breakpoint
CREATE TABLE `shared_records` (
	`id` int AUTO_INCREMENT NOT NULL,
	`doctor_id` int NOT NULL,
	`patient_id` int NOT NULL,
	`record_type` enum('case','vital','diagnosis','prescription','clinical_note','transcription','timeline_event','appointment','consultation','lab_result','imaging') NOT NULL,
	`record_id` int NOT NULL,
	`patient_can_view` boolean DEFAULT true,
	`patient_can_download` boolean DEFAULT false,
	`patient_can_comment` boolean DEFAULT false,
	`hide_from_patient` boolean DEFAULT false,
	`show_after` timestamp,
	`share_reason` text,
	`shared_at` timestamp NOT NULL DEFAULT (now()),
	`viewed_by_patient` boolean DEFAULT false,
	`first_viewed_at` timestamp,
	`last_viewed_at` timestamp,
	`view_count` int DEFAULT 0,
	`revoked_at` timestamp,
	`revocation_reason` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `shared_records_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `subscriptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`plan_type` enum('patient_free','patient_lite','patient_pro','doctor_basic','doctor_premium','enterprise') NOT NULL,
	`price_per_month` decimal(10,2) NOT NULL,
	`currency` varchar(3) NOT NULL DEFAULT 'USD',
	`status` enum('active','trialing','past_due','cancelled','expired') NOT NULL DEFAULT 'active',
	`billing_cycle` enum('monthly','yearly') NOT NULL DEFAULT 'monthly',
	`current_period_start` timestamp NOT NULL,
	`current_period_end` timestamp NOT NULL,
	`trial_start` timestamp,
	`trial_end` timestamp,
	`cancel_at_period_end` boolean DEFAULT false,
	`cancelled_at` timestamp,
	`cancellation_reason` text,
	`stripe_customer_id` varchar(255),
	`stripe_subscription_id` varchar(255),
	`payment_method` enum('stripe','zain_cash','asia_hawala','bank_transfer','cash','manual'),
	`last_payment_date` timestamp,
	`last_payment_amount` decimal(10,2),
	`last_payment_status` enum('succeeded','failed','pending'),
	`next_payment_date` timestamp,
	`next_payment_amount` decimal(10,2),
	`metadata` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `subscriptions_id` PRIMARY KEY(`id`),
	CONSTRAINT `subscriptions_user_id_unique` UNIQUE(`user_id`)
);
--> statement-breakpoint
CREATE TABLE `usage_tracking` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`feature` varchar(100) NOT NULL,
	`count` int NOT NULL DEFAULT 0,
	`period_start` timestamp NOT NULL,
	`period_end` timestamp NOT NULL,
	`limit` int,
	`last_used_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `usage_tracking_id` PRIMARY KEY(`id`)
);
