CREATE TABLE `lab_reference_ranges` (
	`id` int AUTO_INCREMENT NOT NULL,
	`test_name` varchar(255) NOT NULL,
	`test_code` varchar(100),
	`test_category` varchar(100),
	`age_min` int,
	`age_max` int,
	`gender` varchar(20),
	`reference_min` decimal(10,3),
	`reference_max` decimal(10,3),
	`unit` varchar(50) NOT NULL,
	`critical_low` decimal(10,3),
	`critical_high` decimal(10,3),
	`description` text,
	`clinical_context` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lab_reference_ranges_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lab_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`report_date` timestamp NOT NULL,
	`upload_date` timestamp NOT NULL DEFAULT (now()),
	`report_name` varchar(255),
	`lab_name` varchar(255),
	`ordering_physician` varchar(255),
	`file_url` text NOT NULL,
	`file_type` varchar(50),
	`file_size` int,
	`ocr_text` text,
	`extraction_status` varchar(50) DEFAULT 'pending',
	`extraction_error` text,
	`overall_interpretation` text,
	`risk_level` varchar(20),
	`recommended_actions` text,
	`status` varchar(50) DEFAULT 'uploaded',
	`reviewed_by` int,
	`reviewed_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lab_reports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lab_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`report_id` int NOT NULL,
	`user_id` int NOT NULL,
	`test_name` varchar(255) NOT NULL,
	`test_code` varchar(100),
	`test_category` varchar(100),
	`value` varchar(100) NOT NULL,
	`numeric_value` decimal(10,3),
	`unit` varchar(50),
	`reference_range_min` decimal(10,3),
	`reference_range_max` decimal(10,3),
	`reference_range_text` varchar(255),
	`status` varchar(20) NOT NULL,
	`abnormal_flag` boolean DEFAULT false,
	`critical_flag` boolean DEFAULT false,
	`interpretation` text,
	`clinical_significance` text,
	`possible_causes` text,
	`recommended_follow_up` text,
	`test_date` timestamp NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lab_results_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `lab_trends` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`test_name` varchar(255) NOT NULL,
	`trend_direction` varchar(20),
	`percent_change` decimal(10,2),
	`time_span` int,
	`measurement_count` int,
	`first_value` decimal(10,3),
	`last_value` decimal(10,3),
	`min_value` decimal(10,3),
	`max_value` decimal(10,3),
	`avg_value` decimal(10,3),
	`first_date` timestamp,
	`last_date` timestamp,
	`trend_interpretation` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `lab_trends_id` PRIMARY KEY(`id`)
);
