CREATE TABLE `account_activity` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`activity_type` enum('login','logout','password_change','email_change','profile_update','settings_change','failed_login') NOT NULL,
	`ip_address` varchar(45),
	`user_agent` text,
	`device_type` varchar(50),
	`browser` varchar(100),
	`location` varchar(255),
	`success` boolean NOT NULL DEFAULT true,
	`failure_reason` text,
	`metadata` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `account_activity_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `email_preferences` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`welcome_emails` boolean NOT NULL DEFAULT true,
	`verification_emails` boolean NOT NULL DEFAULT true,
	`password_reset_emails` boolean NOT NULL DEFAULT true,
	`security_alerts` boolean NOT NULL DEFAULT true,
	`appointment_confirmations` boolean NOT NULL DEFAULT true,
	`appointment_reminders` boolean NOT NULL DEFAULT true,
	`appointment_reminder_frequency` enum('instant','daily','weekly','off') NOT NULL DEFAULT 'instant',
	`medication_reminders` boolean NOT NULL DEFAULT true,
	`medication_reminder_frequency` enum('instant','daily','weekly','off') NOT NULL DEFAULT 'instant',
	`lab_result_notifications` boolean NOT NULL DEFAULT true,
	`critical_lab_alerts` boolean NOT NULL DEFAULT true,
	`new_message_notifications` boolean NOT NULL DEFAULT true,
	`message_notification_frequency` enum('instant','daily','weekly','off') NOT NULL DEFAULT 'instant',
	`unread_message_digest` boolean NOT NULL DEFAULT false,
	`subscription_confirmations` boolean NOT NULL DEFAULT true,
	`payment_receipts` boolean NOT NULL DEFAULT true,
	`invoice_emails` boolean NOT NULL DEFAULT true,
	`subscription_expiry_warnings` boolean NOT NULL DEFAULT true,
	`payment_failure_alerts` boolean NOT NULL DEFAULT true,
	`quiet_hours_enabled` boolean NOT NULL DEFAULT false,
	`quiet_hours_start` varchar(5) DEFAULT '22:00',
	`quiet_hours_end` varchar(5) DEFAULT '08:00',
	`all_emails_enabled` boolean NOT NULL DEFAULT true,
	`marketing_emails` boolean NOT NULL DEFAULT false,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `email_preferences_id` PRIMARY KEY(`id`),
	CONSTRAINT `email_preferences_user_id_unique` UNIQUE(`user_id`)
);
--> statement-breakpoint
CREATE TABLE `user_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`language` enum('en','ar') NOT NULL DEFAULT 'ar',
	`timezone` varchar(50) NOT NULL DEFAULT 'Asia/Baghdad',
	`date_format` varchar(20) NOT NULL DEFAULT 'DD/MM/YYYY',
	`time_format` enum('12h','24h') NOT NULL DEFAULT '24h',
	`desktop_notifications` boolean NOT NULL DEFAULT true,
	`sound_notifications` boolean NOT NULL DEFAULT true,
	`profile_visibility` enum('public','private','doctors_only') NOT NULL DEFAULT 'doctors_only',
	`show_online_status` boolean NOT NULL DEFAULT true,
	`auto_accept_patients` boolean NOT NULL DEFAULT false,
	`max_daily_consultations` int DEFAULT 20,
	`consultation_duration` int DEFAULT 30,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_settings_user_id_unique` UNIQUE(`user_id`)
);
