CREATE TABLE `epidemiology_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`city` varchar(100),
	`country` varchar(100) DEFAULT 'Iraq',
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`symptom_vector` text NOT NULL,
	`condition` varchar(255),
	`condition_confidence` decimal(5,2),
	`urgency_level` enum('low','moderate','high','emergency'),
	`temperature` decimal(5,2),
	`humidity` decimal(5,2),
	`air_quality_index` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`age_group` varchar(20),
	`gender` enum('male','female','other','unknown'),
	`data_source` varchar(50) DEFAULT 'avicenna_triage',
	`verified` boolean DEFAULT false,
	CONSTRAINT `epidemiology_events_id` PRIMARY KEY(`id`)
);
