CREATE TABLE `wearable_connections` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`device_type` enum('apple_watch','fitbit') NOT NULL,
	`device_id` varchar(255) NOT NULL,
	`device_name` varchar(255),
	`device_model` varchar(100),
	`status` enum('active','disconnected','error') NOT NULL DEFAULT 'active',
	`last_sync_at` timestamp,
	`access_token` text,
	`refresh_token` text,
	`token_expires_at` timestamp,
	`sync_enabled` boolean NOT NULL DEFAULT true,
	`sync_frequency` int NOT NULL DEFAULT 3600,
	`enabled_metrics` text NOT NULL,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `wearable_connections_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `wearable_data_points` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`connection_id` int NOT NULL,
	`metric_type` enum('heart_rate','steps','distance','calories','active_minutes','sleep_duration','sleep_quality','blood_oxygen','hrv','resting_heart_rate','blood_pressure_systolic','blood_pressure_diastolic','respiratory_rate','body_temperature','weight','bmi') NOT NULL,
	`value` decimal(10,2) NOT NULL,
	`unit` varchar(50) NOT NULL,
	`measured_at` timestamp NOT NULL,
	`confidence` decimal(3,2) NOT NULL DEFAULT '1.00',
	`context` text,
	`source_device` varchar(100) NOT NULL,
	`source_app` varchar(100),
	`synced_at` timestamp NOT NULL DEFAULT (now()),
	`external_id` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `wearable_data_points_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `wearable_metrics_summary` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`period_type` enum('daily','weekly','monthly') NOT NULL,
	`period_start` date NOT NULL,
	`period_end` date NOT NULL,
	`avg_heart_rate` decimal(5,2),
	`min_heart_rate` int,
	`max_heart_rate` int,
	`resting_heart_rate` int,
	`avg_hrv` decimal(6,2),
	`total_steps` int,
	`total_distance` decimal(8,2),
	`total_calories` int,
	`total_active_minutes` int,
	`avg_sleep_duration` decimal(4,2),
	`avg_sleep_quality` decimal(3,2),
	`avg_blood_oxygen` decimal(5,2),
	`avg_respiratory_rate` decimal(4,2),
	`avg_systolic` int,
	`avg_diastolic` int,
	`avg_weight` decimal(5,2),
	`avg_bmi` decimal(4,2),
	`avg_body_temp` decimal(4,2),
	`data_completeness` decimal(3,2) NOT NULL DEFAULT '1.00',
	`measurement_count` int NOT NULL DEFAULT 0,
	`anomalies` text,
	`last_updated` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `wearable_metrics_summary_id` PRIMARY KEY(`id`)
);
