CREATE TABLE `orchestration_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`request_id` varchar(255) NOT NULL,
	`user_id` int,
	`session_id` varchar(255),
	`operation` varchar(255) NOT NULL,
	`module` varchar(100) NOT NULL,
	`action` varchar(100) NOT NULL,
	`status` enum('started','in_progress','completed','failed','cancelled') NOT NULL DEFAULT 'started',
	`start_time` timestamp NOT NULL,
	`end_time` timestamp,
	`duration_ms` int,
	`input_data` text,
	`output_data` text,
	`error_message` text,
	`error_stack` text,
	`error_code` varchar(50),
	`memory_usage_mb` decimal(10,2),
	`cpu_usage_percent` decimal(5,2),
	`parent_request_id` varchar(255),
	`depth` int DEFAULT 0,
	`metadata` text,
	`tags` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `orchestration_logs_id` PRIMARY KEY(`id`)
);
