/**
 * BRAIN Performance Testing Suite
 * 100 Clinical Case Scenarios for Diagnostic Accuracy Validation
 * 
 * Categories:
 * - Emergency Cases (20): Life-threatening conditions requiring immediate recognition
 * - Common Conditions (30): Frequently encountered diagnoses in primary care
 * - Complex Cases (20): Multi-system involvement or atypical presentations
 * - Pediatric Cases (10): Age-specific presentations
 * - Geriatric Cases (10): Elderly-specific considerations
 * - Iraqi-Specific Cases (10): Tropical diseases and local prevalence conditions
 */

export interface TestCase {
  id: string;
  category: 'emergency' | 'common' | 'complex' | 'pediatric' | 'geriatric' | 'iraqi-specific';
  difficulty: 'easy' | 'medium' | 'hard';
  patientAge: number;
  patientGender: 'male' | 'female';
  chiefComplaint: string;
  symptoms: string;
  vitals?: {
    bloodPressure?: string;
    heartRate?: number;
    temperature?: number;
    oxygenSaturation?: number;
    respiratoryRate?: number;
  };
  expectedDiagnosis: string;
  expectedUrgency: 'emergency' | 'urgent' | 'semi-urgent' | 'routine';
  expectedConfidence: number; // 0-100
  alternativeDiagnoses?: string[];
  redFlags?: string[];
}

export const testCases: TestCase[] = [
  // ========== EMERGENCY CASES (20) ==========
  {
    id: 'EMG-001',
    category: 'emergency',
    difficulty: 'easy',
    patientAge: 55,
    patientGender: 'male',
    chiefComplaint: 'Severe crushing chest pain',
    symptoms: 'Crushing chest pain radiating to left arm and jaw, started 30 minutes ago, associated with sweating and nausea',
    vitals: {
      bloodPressure: '160/95',
      heartRate: 110,
      temperature: 37.0,
      oxygenSaturation: 94,
    },
    expectedDiagnosis: 'Acute Myocardial Infarction',
    expectedUrgency: 'emergency',
    expectedConfidence: 90,
    alternativeDiagnoses: ['Unstable Angina', 'Aortic Dissection', 'Pulmonary Embolism'],
    redFlags: ['Chest pain radiating to arm', 'Diaphoresis', 'Elevated heart rate'],
  },
  {
    id: 'EMG-002',
    category: 'emergency',
    difficulty: 'easy',
    patientAge: 68,
    patientGender: 'female',
    chiefComplaint: 'Sudden weakness on right side',
    symptoms: 'Sudden onset right-sided weakness, facial droop, slurred speech, started 45 minutes ago',
    vitals: {
      bloodPressure: '180/100',
      heartRate: 88,
      temperature: 36.8,
      oxygenSaturation: 97,
    },
    expectedDiagnosis: 'Acute Ischemic Stroke',
    expectedUrgency: 'emergency',
    expectedConfidence: 95,
    alternativeDiagnoses: ['Hemorrhagic Stroke', 'Transient Ischemic Attack', 'Brain Tumor'],
    redFlags: ['Sudden neurological deficit', 'Facial droop', 'Hypertension'],
  },
  {
    id: 'EMG-003',
    category: 'emergency',
    difficulty: 'medium',
    patientAge: 28,
    patientGender: 'male',
    chiefComplaint: 'Severe difficulty breathing',
    symptoms: 'Sudden onset severe shortness of breath, chest tightness, wheezing, unable to speak full sentences, history of asthma',
    vitals: {
      bloodPressure: '130/85',
      heartRate: 125,
      temperature: 37.2,
      oxygenSaturation: 88,
      respiratoryRate: 32,
    },
    expectedDiagnosis: 'Acute Severe Asthma Exacerbation',
    expectedUrgency: 'emergency',
    expectedConfidence: 92,
    alternativeDiagnoses: ['Anaphylaxis', 'Pneumothorax', 'Pulmonary Embolism'],
    redFlags: ['Oxygen saturation <90%', 'Unable to speak sentences', 'Tachypnea >30'],
  },
  {
    id: 'EMG-004',
    category: 'emergency',
    difficulty: 'medium',
    patientAge: 35,
    patientGender: 'female',
    chiefComplaint: 'Severe abdominal pain',
    symptoms: 'Sudden severe right lower abdominal pain, nausea, vomiting, fever, pain started 8 hours ago and progressively worsening',
    vitals: {
      bloodPressure: '110/70',
      heartRate: 105,
      temperature: 38.5,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Acute Appendicitis',
    expectedUrgency: 'emergency',
    expectedConfidence: 88,
    alternativeDiagnoses: ['Ectopic Pregnancy', 'Ovarian Torsion', 'Kidney Stone'],
    redFlags: ['Fever', 'Progressive pain', 'Right lower quadrant tenderness'],
  },
  {
    id: 'EMG-005',
    category: 'emergency',
    difficulty: 'hard',
    patientAge: 42,
    patientGender: 'male',
    chiefComplaint: 'Confusion and excessive urination',
    symptoms: 'Confusion, excessive thirst and urination for 2 days, fruity breath odor, nausea, vomiting, known diabetic',
    vitals: {
      bloodPressure: '95/60',
      heartRate: 115,
      temperature: 37.5,
      oxygenSaturation: 99,
      respiratoryRate: 28,
    },
    expectedDiagnosis: 'Diabetic Ketoacidosis',
    expectedUrgency: 'emergency',
    expectedConfidence: 93,
    alternativeDiagnoses: ['Hyperosmolar Hyperglycemic State', 'Sepsis', 'Meningitis'],
    redFlags: ['Altered mental status', 'Kussmaul breathing', 'Hypotension'],
  },
  {
    id: 'EMG-006',
    category: 'emergency',
    difficulty: 'medium',
    patientAge: 72,
    patientGender: 'male',
    chiefComplaint: 'Sudden severe headache',
    symptoms: 'Sudden onset worst headache of life, started during exercise, associated with neck stiffness and photophobia',
    vitals: {
      bloodPressure: '190/110',
      heartRate: 92,
      temperature: 37.0,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Subarachnoid Hemorrhage',
    expectedUrgency: 'emergency',
    expectedConfidence: 90,
    alternativeDiagnoses: ['Meningitis', 'Migraine', 'Hypertensive Emergency'],
    redFlags: ['Thunderclap headache', 'Neck stiffness', 'Severe hypertension'],
  },
  {
    id: 'EMG-007',
    category: 'emergency',
    difficulty: 'medium',
    patientAge: 58,
    patientGender: 'female',
    chiefComplaint: 'Sudden leg swelling and chest pain',
    symptoms: 'Left leg swelling and pain for 3 days, now sudden onset chest pain and shortness of breath, recent long flight',
    vitals: {
      bloodPressure: '100/65',
      heartRate: 118,
      temperature: 37.3,
      oxygenSaturation: 91,
      respiratoryRate: 26,
    },
    expectedDiagnosis: 'Pulmonary Embolism',
    expectedUrgency: 'emergency',
    expectedConfidence: 89,
    alternativeDiagnoses: ['Pneumonia', 'Myocardial Infarction', 'Pneumothorax'],
    redFlags: ['Hypoxia', 'Tachycardia', 'Recent immobilization'],
  },
  {
    id: 'EMG-008',
    category: 'emergency',
    difficulty: 'hard',
    patientAge: 65,
    patientGender: 'male',
    chiefComplaint: 'Severe abdominal pain and vomiting',
    symptoms: 'Severe diffuse abdominal pain, multiple episodes of vomiting, no bowel movement for 3 days, previous abdominal surgery',
    vitals: {
      bloodPressure: '90/55',
      heartRate: 125,
      temperature: 38.2,
      oxygenSaturation: 96,
    },
    expectedDiagnosis: 'Bowel Obstruction',
    expectedUrgency: 'emergency',
    expectedConfidence: 87,
    alternativeDiagnoses: ['Mesenteric Ischemia', 'Perforated Viscus', 'Pancreatitis'],
    redFlags: ['Hypotension', 'Tachycardia', 'No bowel movement'],
  },
  {
    id: 'EMG-009',
    category: 'emergency',
    difficulty: 'medium',
    patientAge: 45,
    patientGender: 'female',
    chiefComplaint: 'Severe headache and blurred vision',
    symptoms: 'Severe headache, blurred vision, nausea, blood pressure very high, 32 weeks pregnant',
    vitals: {
      bloodPressure: '170/115',
      heartRate: 95,
      temperature: 37.1,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Severe Preeclampsia',
    expectedUrgency: 'emergency',
    expectedConfidence: 94,
    alternativeDiagnoses: ['Eclampsia', 'Hypertensive Emergency', 'HELLP Syndrome'],
    redFlags: ['Severe hypertension in pregnancy', 'Visual changes', 'Headache'],
  },
  {
    id: 'EMG-010',
    category: 'emergency',
    difficulty: 'hard',
    patientAge: 52,
    patientGender: 'male',
    chiefComplaint: 'Fever and confusion',
    symptoms: 'High fever, confusion, rapid breathing, chills, known urinary tract infection on antibiotics for 2 days',
    vitals: {
      bloodPressure: '85/50',
      heartRate: 135,
      temperature: 39.5,
      oxygenSaturation: 93,
      respiratoryRate: 30,
    },
    expectedDiagnosis: 'Septic Shock',
    expectedUrgency: 'emergency',
    expectedConfidence: 92,
    alternativeDiagnoses: ['Severe Sepsis', 'Meningitis', 'Pneumonia with Sepsis'],
    redFlags: ['Hypotension', 'Altered mental status', 'High fever'],
  },
  {
    id: 'EMG-011',
    category: 'emergency',
    difficulty: 'medium',
    patientAge: 8,
    patientGender: 'male',
    chiefComplaint: 'Difficulty breathing after bee sting',
    symptoms: 'Bee sting 10 minutes ago, now difficulty breathing, facial swelling, hives all over body, throat feels tight',
    vitals: {
      bloodPressure: '80/50',
      heartRate: 140,
      temperature: 37.0,
      oxygenSaturation: 89,
      respiratoryRate: 35,
    },
    expectedDiagnosis: 'Anaphylaxis',
    expectedUrgency: 'emergency',
    expectedConfidence: 98,
    alternativeDiagnoses: ['Severe Allergic Reaction', 'Angioedema'],
    redFlags: ['Hypotension', 'Respiratory distress', 'Rapid onset after exposure'],
  },
  {
    id: 'EMG-012',
    category: 'emergency',
    difficulty: 'hard',
    patientAge: 70,
    patientGender: 'male',
    chiefComplaint: 'Severe back pain',
    symptoms: 'Sudden severe tearing back pain radiating to abdomen, history of hypertension, feels faint',
    vitals: {
      bloodPressure: '180/100 right arm, 140/85 left arm',
      heartRate: 105,
      temperature: 36.9,
      oxygenSaturation: 97,
    },
    expectedDiagnosis: 'Aortic Dissection',
    expectedUrgency: 'emergency',
    expectedConfidence: 88,
    alternativeDiagnoses: ['Myocardial Infarction', 'Pulmonary Embolism', 'Renal Colic'],
    redFlags: ['Blood pressure differential', 'Tearing pain', 'Radiation to abdomen'],
  },
  {
    id: 'EMG-013',
    category: 'emergency',
    difficulty: 'medium',
    patientAge: 25,
    patientGender: 'female',
    chiefComplaint: 'Severe abdominal pain and missed period',
    symptoms: 'Severe lower abdominal pain, missed period by 2 weeks, vaginal spotting, feels dizzy when standing',
    vitals: {
      bloodPressure: '90/60',
      heartRate: 115,
      temperature: 37.2,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Ruptured Ectopic Pregnancy',
    expectedUrgency: 'emergency',
    expectedConfidence: 90,
    alternativeDiagnoses: ['Ovarian Cyst Rupture', 'Appendicitis', 'Miscarriage'],
    redFlags: ['Hypotension', 'Tachycardia', 'Missed period with pain'],
  },
  {
    id: 'EMG-014',
    category: 'emergency',
    difficulty: 'hard',
    patientAge: 60,
    patientGender: 'male',
    chiefComplaint: 'Vomiting blood',
    symptoms: 'Vomiting large amounts of bright red blood, history of liver cirrhosis and alcohol use, feels weak and dizzy',
    vitals: {
      bloodPressure: '85/55',
      heartRate: 130,
      temperature: 37.0,
      oxygenSaturation: 95,
    },
    expectedDiagnosis: 'Esophageal Variceal Bleeding',
    expectedUrgency: 'emergency',
    expectedConfidence: 91,
    alternativeDiagnoses: ['Peptic Ulcer Bleeding', 'Mallory-Weiss Tear', 'Gastric Cancer'],
    redFlags: ['Hematemesis', 'Hypotension', 'Known liver disease'],
  },
  {
    id: 'EMG-015',
    category: 'emergency',
    difficulty: 'medium',
    patientAge: 18,
    patientGender: 'male',
    chiefComplaint: 'Sudden severe testicular pain',
    symptoms: 'Sudden onset severe left testicular pain, started 2 hours ago, nausea, no trauma',
    vitals: {
      bloodPressure: '125/80',
      heartRate: 100,
      temperature: 37.1,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Testicular Torsion',
    expectedUrgency: 'emergency',
    expectedConfidence: 89,
    alternativeDiagnoses: ['Epididymitis', 'Orchitis', 'Inguinal Hernia'],
    redFlags: ['Sudden severe pain', 'No trauma', 'Young age'],
  },
  {
    id: 'EMG-016',
    category: 'emergency',
    difficulty: 'hard',
    patientAge: 55,
    patientGender: 'female',
    chiefComplaint: 'Sudden vision loss',
    symptoms: 'Sudden painless loss of vision in right eye, like a curtain coming down, no headache, history of atrial fibrillation',
    vitals: {
      bloodPressure: '145/90',
      heartRate: 95,
      temperature: 36.8,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Central Retinal Artery Occlusion',
    expectedUrgency: 'emergency',
    expectedConfidence: 87,
    alternativeDiagnoses: ['Retinal Detachment', 'Vitreous Hemorrhage', 'Stroke'],
    redFlags: ['Sudden painless vision loss', 'Atrial fibrillation', 'Curtain-like'],
  },
  {
    id: 'EMG-017',
    category: 'emergency',
    difficulty: 'medium',
    patientAge: 3,
    patientGender: 'female',
    chiefComplaint: 'High fever and seizure',
    symptoms: 'High fever for 1 day, just had a seizure lasting 3 minutes, now drowsy, neck seems stiff',
    vitals: {
      bloodPressure: '90/60',
      heartRate: 150,
      temperature: 40.0,
      oxygenSaturation: 97,
    },
    expectedDiagnosis: 'Bacterial Meningitis',
    expectedUrgency: 'emergency',
    expectedConfidence: 88,
    alternativeDiagnoses: ['Febrile Seizure', 'Viral Meningitis', 'Encephalitis'],
    redFlags: ['High fever', 'Seizure', 'Neck stiffness in child'],
  },
  {
    id: 'EMG-018',
    category: 'emergency',
    difficulty: 'hard',
    patientAge: 48,
    patientGender: 'male',
    chiefComplaint: 'Severe eye pain and blurred vision',
    symptoms: 'Severe right eye pain, blurred vision, seeing halos around lights, nausea, eye appears red',
    vitals: {
      bloodPressure: '140/85',
      heartRate: 88,
      temperature: 37.0,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Acute Angle-Closure Glaucoma',
    expectedUrgency: 'emergency',
    expectedConfidence: 90,
    alternativeDiagnoses: ['Uveitis', 'Corneal Ulcer', 'Migraine'],
    redFlags: ['Severe eye pain', 'Halos', 'Red eye'],
  },
  {
    id: 'EMG-019',
    category: 'emergency',
    difficulty: 'medium',
    patientAge: 32,
    patientGender: 'male',
    chiefComplaint: 'Severe chest pain after car accident',
    symptoms: 'Car accident 30 minutes ago, severe chest pain, difficulty breathing, bruising on chest',
    vitals: {
      bloodPressure: '100/70',
      heartRate: 120,
      temperature: 36.5,
      oxygenSaturation: 90,
      respiratoryRate: 28,
    },
    expectedDiagnosis: 'Pneumothorax',
    expectedUrgency: 'emergency',
    expectedConfidence: 91,
    alternativeDiagnoses: ['Hemothorax', 'Rib Fractures', 'Pulmonary Contusion'],
    redFlags: ['Trauma', 'Hypoxia', 'Respiratory distress'],
  },
  {
    id: 'EMG-020',
    category: 'emergency',
    difficulty: 'hard',
    patientAge: 75,
    patientGender: 'female',
    chiefComplaint: 'Sudden severe abdominal pain',
    symptoms: 'Sudden severe abdominal pain, known abdominal aortic aneurysm, feels faint, pain radiating to back',
    vitals: {
      bloodPressure: '80/50',
      heartRate: 135,
      temperature: 36.0,
      oxygenSaturation: 94,
    },
    expectedDiagnosis: 'Ruptured Abdominal Aortic Aneurysm',
    expectedUrgency: 'emergency',
    expectedConfidence: 93,
    alternativeDiagnoses: ['Mesenteric Ischemia', 'Perforated Viscus', 'Renal Colic'],
    redFlags: ['Known AAA', 'Hypotension', 'Back pain'],
  },

  // ========== COMMON CONDITIONS (30) ==========
  {
    id: 'COM-001',
    category: 'common',
    difficulty: 'easy',
    patientAge: 30,
    patientGender: 'female',
    chiefComplaint: 'Fever and cough',
    symptoms: 'Fever for 3 days, productive cough with yellow sputum, chest pain when breathing, shortness of breath',
    vitals: {
      bloodPressure: '120/75',
      heartRate: 95,
      temperature: 38.8,
      oxygenSaturation: 94,
      respiratoryRate: 22,
    },
    expectedDiagnosis: 'Community-Acquired Pneumonia',
    expectedUrgency: 'urgent',
    expectedConfidence: 88,
    alternativeDiagnoses: ['Bronchitis', 'COVID-19', 'Tuberculosis'],
  },
  {
    id: 'COM-002',
    category: 'common',
    difficulty: 'easy',
    patientAge: 25,
    patientGender: 'female',
    chiefComplaint: 'Burning urination',
    symptoms: 'Burning sensation when urinating, increased frequency, lower abdominal discomfort, no fever',
    vitals: {
      bloodPressure: '115/70',
      heartRate: 78,
      temperature: 37.2,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Urinary Tract Infection',
    expectedUrgency: 'routine',
    expectedConfidence: 90,
    alternativeDiagnoses: ['Cystitis', 'Pyelonephritis', 'Urethritis'],
  },
  {
    id: 'COM-003',
    category: 'common',
    difficulty: 'easy',
    patientAge: 40,
    patientGender: 'male',
    chiefComplaint: 'Heartburn and chest discomfort',
    symptoms: 'Burning sensation in chest after meals, worse when lying down, sour taste in mouth, no radiation to arms',
    vitals: {
      bloodPressure: '130/80',
      heartRate: 72,
      temperature: 36.8,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Gastroesophageal Reflux Disease',
    expectedUrgency: 'routine',
    expectedConfidence: 85,
    alternativeDiagnoses: ['Peptic Ulcer', 'Angina', 'Esophagitis'],
  },
  {
    id: 'COM-004',
    category: 'common',
    difficulty: 'medium',
    patientAge: 55,
    patientGender: 'male',
    chiefComplaint: 'Increased thirst and urination',
    symptoms: 'Increased thirst and urination for 2 months, unexplained weight loss, fatigue, blurred vision occasionally',
    vitals: {
      bloodPressure: '135/85',
      heartRate: 80,
      temperature: 36.9,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Type 2 Diabetes Mellitus',
    expectedUrgency: 'semi-urgent',
    expectedConfidence: 92,
    alternativeDiagnoses: ['Type 1 Diabetes', 'Diabetes Insipidus', 'Hyperthyroidism'],
  },
  {
    id: 'COM-005',
    category: 'common',
    difficulty: 'easy',
    patientAge: 35,
    patientGender: 'female',
    chiefComplaint: 'Severe headache',
    symptoms: 'Throbbing headache on one side, nausea, sensitivity to light and sound, lasted 6 hours, history of similar headaches',
    vitals: {
      bloodPressure: '125/78',
      heartRate: 75,
      temperature: 36.7,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Migraine',
    expectedUrgency: 'routine',
    expectedConfidence: 87,
    alternativeDiagnoses: ['Tension Headache', 'Cluster Headache', 'Sinusitis'],
  },
  {
    id: 'COM-006',
    category: 'common',
    difficulty: 'easy',
    patientAge: 28,
    patientGender: 'male',
    chiefComplaint: 'Diarrhea and vomiting',
    symptoms: 'Watery diarrhea 6 times today, vomiting 3 times, abdominal cramping, ate at restaurant yesterday',
    vitals: {
      bloodPressure: '110/70',
      heartRate: 90,
      temperature: 37.8,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Acute Gastroenteritis',
    expectedUrgency: 'routine',
    expectedConfidence: 88,
    alternativeDiagnoses: ['Food Poisoning', 'Viral Gastroenteritis', 'Bacterial Enteritis'],
  },
  {
    id: 'COM-007',
    category: 'common',
    difficulty: 'medium',
    patientAge: 50,
    patientGender: 'female',
    chiefComplaint: 'Joint pain and stiffness',
    symptoms: 'Pain and stiffness in both hands and knees, worse in the morning, lasts about 30 minutes, swelling in finger joints',
    vitals: {
      bloodPressure: '128/82',
      heartRate: 76,
      temperature: 36.8,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Rheumatoid Arthritis',
    expectedUrgency: 'semi-urgent',
    expectedConfidence: 83,
    alternativeDiagnoses: ['Osteoarthritis', 'Psoriatic Arthritis', 'Lupus'],
  },
  {
    id: 'COM-008',
    category: 'common',
    difficulty: 'easy',
    patientAge: 22,
    patientGender: 'female',
    chiefComplaint: 'Sore throat and fever',
    symptoms: 'Severe sore throat, difficulty swallowing, fever, white patches on tonsils, swollen neck glands',
    vitals: {
      bloodPressure: '118/72',
      heartRate: 88,
      temperature: 38.5,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Streptococcal Pharyngitis',
    expectedUrgency: 'routine',
    expectedConfidence: 86,
    alternativeDiagnoses: ['Viral Pharyngitis', 'Mononucleosis', 'Tonsillitis'],
  },
  {
    id: 'COM-009',
    category: 'common',
    difficulty: 'medium',
    patientAge: 60,
    patientGender: 'male',
    chiefComplaint: 'High blood pressure',
    symptoms: 'Headache, no other symptoms, blood pressure measured at pharmacy was 165/100, no previous diagnosis',
    vitals: {
      bloodPressure: '168/102',
      heartRate: 82,
      temperature: 36.9,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Essential Hypertension',
    expectedUrgency: 'semi-urgent',
    expectedConfidence: 85,
    alternativeDiagnoses: ['Secondary Hypertension', 'White Coat Hypertension', 'Hypertensive Urgency'],
  },
  {
    id: 'COM-010',
    category: 'common',
    difficulty: 'easy',
    patientAge: 45,
    patientGender: 'female',
    chiefComplaint: 'Fatigue and weight gain',
    symptoms: 'Extreme fatigue, weight gain despite no change in diet, feeling cold all the time, dry skin, constipation',
    vitals: {
      bloodPressure: '125/80',
      heartRate: 62,
      temperature: 36.2,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Hypothyroidism',
    expectedUrgency: 'routine',
    expectedConfidence: 88,
    alternativeDiagnoses: ['Depression', 'Anemia', 'Chronic Fatigue Syndrome'],
  },
  {
    id: 'COM-011',
    category: 'common',
    difficulty: 'easy',
    patientAge: 38,
    patientGender: 'male',
    chiefComplaint: 'Lower back pain',
    symptoms: 'Lower back pain for 3 days, started after lifting heavy object, pain worse with movement, no leg numbness',
    vitals: {
      bloodPressure: '130/78',
      heartRate: 74,
      temperature: 36.8,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Acute Lumbar Strain',
    expectedUrgency: 'routine',
    expectedConfidence: 84,
    alternativeDiagnoses: ['Herniated Disc', 'Muscle Spasm', 'Sciatica'],
  },
  {
    id: 'COM-012',
    category: 'common',
    difficulty: 'medium',
    patientAge: 32,
    patientGender: 'female',
    chiefComplaint: 'Anxiety and palpitations',
    symptoms: 'Frequent episodes of rapid heartbeat, sweating, trembling, feeling of impending doom, difficulty sleeping',
    vitals: {
      bloodPressure: '135/88',
      heartRate: 105,
      temperature: 36.9,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Panic Disorder',
    expectedUrgency: 'routine',
    expectedConfidence: 82,
    alternativeDiagnoses: ['Generalized Anxiety Disorder', 'Hyperthyroidism', 'Cardiac Arrhythmia'],
  },
  {
    id: 'COM-013',
    category: 'common',
    difficulty: 'easy',
    patientAge: 26,
    patientGender: 'female',
    chiefComplaint: 'Vaginal itching and discharge',
    symptoms: 'Vaginal itching, thick white discharge like cottage cheese, no odor, some burning',
    vitals: {
      bloodPressure: '115/72',
      heartRate: 76,
      temperature: 36.8,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Vaginal Candidiasis',
    expectedUrgency: 'routine',
    expectedConfidence: 89,
    alternativeDiagnoses: ['Bacterial Vaginosis', 'Trichomoniasis', 'Contact Dermatitis'],
  },
  {
    id: 'COM-014',
    category: 'common',
    difficulty: 'medium',
    patientAge: 58,
    patientGender: 'male',
    chiefComplaint: 'Frequent nighttime urination',
    symptoms: 'Waking up 4-5 times per night to urinate, weak urine stream, difficulty starting urination, feeling of incomplete emptying',
    vitals: {
      bloodPressure: '132/84',
      heartRate: 72,
      temperature: 36.7,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Benign Prostatic Hyperplasia',
    expectedUrgency: 'routine',
    expectedConfidence: 87,
    alternativeDiagnoses: ['Prostatitis', 'Prostate Cancer', 'Urinary Tract Infection'],
  },
  {
    id: 'COM-015',
    category: 'common',
    difficulty: 'easy',
    patientAge: 42,
    patientGender: 'female',
    chiefComplaint: 'Facial pain and nasal congestion',
    symptoms: 'Facial pain and pressure, especially around eyes and forehead, thick yellow nasal discharge, headache, symptoms for 10 days',
    vitals: {
      bloodPressure: '122/76',
      heartRate: 78,
      temperature: 37.5,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Acute Bacterial Sinusitis',
    expectedUrgency: 'routine',
    expectedConfidence: 86,
    alternativeDiagnoses: ['Viral Sinusitis', 'Allergic Rhinitis', 'Migraine'],
  },
  {
    id: 'COM-016',
    category: 'common',
    difficulty: 'medium',
    patientAge: 48,
    patientGender: 'male',
    chiefComplaint: 'Chest discomfort with exertion',
    symptoms: 'Chest pressure when walking uphill, relieved by rest, lasts 2-3 minutes, no pain at rest, history of high cholesterol',
    vitals: {
      bloodPressure: '145/90',
      heartRate: 76,
      temperature: 36.8,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Stable Angina',
    expectedUrgency: 'semi-urgent',
    expectedConfidence: 85,
    alternativeDiagnoses: ['Coronary Artery Disease', 'Costochondritis', 'GERD'],
  },
  {
    id: 'COM-017',
    category: 'common',
    difficulty: 'easy',
    patientAge: 35,
    patientGender: 'male',
    chiefComplaint: 'Itchy rash',
    symptoms: 'Itchy red rash on arms and legs, started after using new laundry detergent, no fever, rash is raised and red',
    vitals: {
      bloodPressure: '120/75',
      heartRate: 72,
      temperature: 36.7,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Contact Dermatitis',
    expectedUrgency: 'routine',
    expectedConfidence: 88,
    alternativeDiagnoses: ['Allergic Reaction', 'Eczema', 'Urticaria'],
  },
  {
    id: 'COM-018',
    category: 'common',
    difficulty: 'medium',
    patientAge: 52,
    patientGender: 'female',
    chiefComplaint: 'Hot flashes and irregular periods',
    symptoms: 'Hot flashes multiple times per day, night sweats, irregular periods for 6 months, mood swings, age 52',
    vitals: {
      bloodPressure: '128/80',
      heartRate: 78,
      temperature: 36.9,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Menopause',
    expectedUrgency: 'routine',
    expectedConfidence: 91,
    alternativeDiagnoses: ['Perimenopause', 'Hyperthyroidism', 'Anxiety'],
  },
  {
    id: 'COM-019',
    category: 'common',
    difficulty: 'easy',
    patientAge: 29,
    patientGender: 'male',
    chiefComplaint: 'Heel pain',
    symptoms: 'Sharp pain in heel, especially with first steps in the morning, pain improves with walking, worse after rest',
    vitals: {
      bloodPressure: '125/78',
      heartRate: 70,
      temperature: 36.8,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Plantar Fasciitis',
    expectedUrgency: 'routine',
    expectedConfidence: 87,
    alternativeDiagnoses: ['Heel Spur', 'Achilles Tendinitis', 'Stress Fracture'],
  },
  {
    id: 'COM-020',
    category: 'common',
    difficulty: 'medium',
    patientAge: 65,
    patientGender: 'female',
    chiefComplaint: 'Swollen ankles',
    symptoms: 'Both ankles swollen, worse at end of day, shortness of breath when climbing stairs, sleeping with 2 pillows',
    vitals: {
      bloodPressure: '138/88',
      heartRate: 88,
      temperature: 36.7,
      oxygenSaturation: 95,
    },
    expectedDiagnosis: 'Congestive Heart Failure',
    expectedUrgency: 'semi-urgent',
    expectedConfidence: 84,
    alternativeDiagnoses: ['Venous Insufficiency', 'Kidney Disease', 'Liver Disease'],
  },
  {
    id: 'COM-021',
    category: 'common',
    difficulty: 'easy',
    patientAge: 24,
    patientGender: 'female',
    chiefComplaint: 'Acne breakout',
    symptoms: 'Multiple pimples on face, some with pus, worse before menstrual period, tried over-the-counter treatments',
    vitals: {
      bloodPressure: '115/70',
      heartRate: 72,
      temperature: 36.8,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Acne Vulgaris',
    expectedUrgency: 'routine',
    expectedConfidence: 90,
    alternativeDiagnoses: ['Rosacea', 'Folliculitis', 'Hormonal Acne'],
  },
  {
    id: 'COM-022',
    category: 'common',
    difficulty: 'medium',
    patientAge: 70,
    patientGender: 'male',
    chiefComplaint: 'Memory problems',
    symptoms: 'Forgetting recent conversations, difficulty finding words, family noticed changes over past year, getting lost in familiar places',
    vitals: {
      bloodPressure: '135/82',
      heartRate: 74,
      temperature: 36.8,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Alzheimer\'s Disease',
    expectedUrgency: 'semi-urgent',
    expectedConfidence: 80,
    alternativeDiagnoses: ['Vascular Dementia', 'Normal Aging', 'Depression'],
  },
  {
    id: 'COM-023',
    category: 'common',
    difficulty: 'easy',
    patientAge: 33,
    patientGender: 'male',
    chiefComplaint: 'Athlete\'s foot',
    symptoms: 'Itchy, peeling skin between toes, some redness, uses public gym showers, symptoms for 2 weeks',
    vitals: {
      bloodPressure: '122/76',
      heartRate: 70,
      temperature: 36.7,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Tinea Pedis',
    expectedUrgency: 'routine',
    expectedConfidence: 92,
    alternativeDiagnoses: ['Bacterial Infection', 'Contact Dermatitis', 'Eczema'],
  },
  {
    id: 'COM-024',
    category: 'common',
    difficulty: 'medium',
    patientAge: 44,
    patientGender: 'female',
    chiefComplaint: 'Persistent sadness',
    symptoms: 'Feeling sad most days for 2 months, loss of interest in activities, poor sleep, low energy, difficulty concentrating',
    vitals: {
      bloodPressure: '118/74',
      heartRate: 76,
      temperature: 36.8,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Major Depressive Disorder',
    expectedUrgency: 'semi-urgent',
    expectedConfidence: 85,
    alternativeDiagnoses: ['Adjustment Disorder', 'Hypothyroidism', 'Chronic Fatigue'],
  },
  {
    id: 'COM-025',
    category: 'common',
    difficulty: 'easy',
    patientAge: 27,
    patientGender: 'male',
    chiefComplaint: 'Pink eye',
    symptoms: 'Red, itchy eye, sticky yellow discharge, especially in morning, vision normal, one eye affected',
    vitals: {
      bloodPressure: '120/75',
      heartRate: 72,
      temperature: 36.9,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Bacterial Conjunctivitis',
    expectedUrgency: 'routine',
    expectedConfidence: 89,
    alternativeDiagnoses: ['Viral Conjunctivitis', 'Allergic Conjunctivitis', 'Blepharitis'],
  },
  {
    id: 'COM-026',
    category: 'common',
    difficulty: 'medium',
    patientAge: 56,
    patientGender: 'male',
    chiefComplaint: 'Gout attack',
    symptoms: 'Sudden severe pain in big toe, red, swollen, extremely tender to touch, started overnight, history of similar episodes',
    vitals: {
      bloodPressure: '142/88',
      heartRate: 82,
      temperature: 37.2,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Acute Gout',
    expectedUrgency: 'routine',
    expectedConfidence: 91,
    alternativeDiagnoses: ['Septic Arthritis', 'Pseudogout', 'Trauma'],
  },
  {
    id: 'COM-027',
    category: 'common',
    difficulty: 'easy',
    patientAge: 19,
    patientGender: 'female',
    chiefComplaint: 'Painful menstrual cramps',
    symptoms: 'Severe lower abdominal cramping during period, nausea, pain radiating to lower back, interferes with daily activities',
    vitals: {
      bloodPressure: '115/70',
      heartRate: 78,
      temperature: 36.8,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Primary Dysmenorrhea',
    expectedUrgency: 'routine',
    expectedConfidence: 88,
    alternativeDiagnoses: ['Endometriosis', 'Pelvic Inflammatory Disease', 'Ovarian Cyst'],
  },
  {
    id: 'COM-028',
    category: 'common',
    difficulty: 'medium',
    patientAge: 62,
    patientGender: 'female',
    chiefComplaint: 'Dry eyes',
    symptoms: 'Eyes feel dry and gritty, burning sensation, worse in air conditioning, also has dry mouth',
    vitals: {
      bloodPressure: '128/80',
      heartRate: 74,
      temperature: 36.8,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Sjögren\'s Syndrome',
    expectedUrgency: 'routine',
    expectedConfidence: 78,
    alternativeDiagnoses: ['Dry Eye Syndrome', 'Blepharitis', 'Medication Side Effect'],
  },
  {
    id: 'COM-029',
    category: 'common',
    difficulty: 'easy',
    patientAge: 36,
    patientGender: 'male',
    chiefComplaint: 'Hemorrhoids',
    symptoms: 'Bright red blood on toilet paper, painful lump near anus, pain with bowel movements, constipation',
    vitals: {
      bloodPressure: '125/78',
      heartRate: 72,
      temperature: 36.7,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'External Hemorrhoids',
    expectedUrgency: 'routine',
    expectedConfidence: 87,
    alternativeDiagnoses: ['Anal Fissure', 'Rectal Prolapse', 'Colorectal Cancer'],
  },
  {
    id: 'COM-030',
    category: 'common',
    difficulty: 'medium',
    patientAge: 41,
    patientGender: 'female',
    chiefComplaint: 'Carpal tunnel symptoms',
    symptoms: 'Numbness and tingling in thumb, index, and middle fingers, worse at night, hand weakness, works as typist',
    vitals: {
      bloodPressure: '120/76',
      heartRate: 70,
      temperature: 36.8,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Carpal Tunnel Syndrome',
    expectedUrgency: 'routine',
    expectedConfidence: 89,
    alternativeDiagnoses: ['Cervical Radiculopathy', 'Peripheral Neuropathy', 'Tendinitis'],
  },

  // ========== COMPLEX CASES (20) ==========
  {
    id: 'CPX-001',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 58,
    patientGender: 'male',
    chiefComplaint: 'Fatigue and weight loss',
    symptoms: 'Progressive fatigue for 3 months, unintentional weight loss of 10kg, night sweats, enlarged lymph nodes in neck',
    vitals: {
      bloodPressure: '115/70',
      heartRate: 88,
      temperature: 37.8,
      oxygenSaturation: 97,
    },
    expectedDiagnosis: 'Lymphoma',
    expectedUrgency: 'urgent',
    expectedConfidence: 75,
    alternativeDiagnoses: ['Tuberculosis', 'HIV/AIDS', 'Chronic Infection'],
  },
  {
    id: 'CPX-002',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 45,
    patientGender: 'female',
    chiefComplaint: 'Multiple joint pain and rash',
    symptoms: 'Joint pain in hands, wrists, knees, butterfly rash on face, fatigue, hair loss, mouth ulcers',
    vitals: {
      bloodPressure: '125/82',
      heartRate: 85,
      temperature: 37.5,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Systemic Lupus Erythematosus',
    expectedUrgency: 'urgent',
    expectedConfidence: 82,
    alternativeDiagnoses: ['Rheumatoid Arthritis', 'Mixed Connective Tissue Disease', 'Dermatomyositis'],
  },
  {
    id: 'CPX-003',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 62,
    patientGender: 'male',
    chiefComplaint: 'Confusion and tremor',
    symptoms: 'Progressive confusion over weeks, tremor in hands, difficulty walking, yellow skin, history of heavy alcohol use',
    vitals: {
      bloodPressure: '100/65',
      heartRate: 92,
      temperature: 37.2,
      oxygenSaturation: 96,
    },
    expectedDiagnosis: 'Hepatic Encephalopathy',
    expectedUrgency: 'urgent',
    expectedConfidence: 85,
    alternativeDiagnoses: ['Wernicke Encephalopathy', 'Parkinson\'s Disease', 'Dementia'],
  },
  {
    id: 'CPX-004',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 38,
    patientGender: 'female',
    chiefComplaint: 'Muscle weakness',
    symptoms: 'Progressive muscle weakness, double vision worse in evening, difficulty swallowing, drooping eyelids',
    vitals: {
      bloodPressure: '118/74',
      heartRate: 76,
      temperature: 36.8,
      oxygenSaturation: 97,
    },
    expectedDiagnosis: 'Myasthenia Gravis',
    expectedUrgency: 'urgent',
    expectedConfidence: 80,
    alternativeDiagnoses: ['Lambert-Eaton Syndrome', 'Botulism', 'Multiple Sclerosis'],
  },
  {
    id: 'CPX-005',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 55,
    patientGender: 'male',
    chiefComplaint: 'Chronic cough and weight loss',
    symptoms: 'Persistent cough for 3 months, coughing up blood occasionally, weight loss, smoker for 30 years, chest pain',
    vitals: {
      bloodPressure: '130/85',
      heartRate: 90,
      temperature: 37.3,
      oxygenSaturation: 93,
    },
    expectedDiagnosis: 'Lung Cancer',
    expectedUrgency: 'urgent',
    expectedConfidence: 78,
    alternativeDiagnoses: ['Tuberculosis', 'Chronic Bronchitis', 'Pneumonia'],
  },
  {
    id: 'CPX-006',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 48,
    patientGender: 'female',
    chiefComplaint: 'Numbness and vision problems',
    symptoms: 'Episodes of numbness in limbs, blurred vision in one eye, fatigue, symptoms come and go over months',
    vitals: {
      bloodPressure: '122/78',
      heartRate: 74,
      temperature: 36.9,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Multiple Sclerosis',
    expectedUrgency: 'urgent',
    expectedConfidence: 77,
    alternativeDiagnoses: ['Neuromyelitis Optica', 'Vitamin B12 Deficiency', 'Brain Tumor'],
  },
  {
    id: 'CPX-007',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 35,
    patientGender: 'male',
    chiefComplaint: 'Severe abdominal pain and diarrhea',
    symptoms: 'Chronic bloody diarrhea, severe abdominal cramping, weight loss, urgency, symptoms for 6 months',
    vitals: {
      bloodPressure: '110/70',
      heartRate: 95,
      temperature: 37.8,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Ulcerative Colitis',
    expectedUrgency: 'urgent',
    expectedConfidence: 81,
    alternativeDiagnoses: ['Crohn\'s Disease', 'Infectious Colitis', 'Colorectal Cancer'],
  },
  {
    id: 'CPX-008',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 52,
    patientGender: 'female',
    chiefComplaint: 'Swollen legs and foamy urine',
    symptoms: 'Bilateral leg swelling, foamy urine, fatigue, decreased urine output, history of diabetes',
    vitals: {
      bloodPressure: '155/95',
      heartRate: 82,
      temperature: 36.8,
      oxygenSaturation: 97,
    },
    expectedDiagnosis: 'Nephrotic Syndrome',
    expectedUrgency: 'urgent',
    expectedConfidence: 83,
    alternativeDiagnoses: ['Chronic Kidney Disease', 'Heart Failure', 'Liver Cirrhosis'],
  },
  {
    id: 'CPX-009',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 40,
    patientGender: 'male',
    chiefComplaint: 'Severe headaches and vision changes',
    symptoms: 'Severe headaches, vision changes, excessive thirst and urination, erectile dysfunction, enlarged hands and feet',
    vitals: {
      bloodPressure: '148/92',
      heartRate: 78,
      temperature: 36.9,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Acromegaly',
    expectedUrgency: 'semi-urgent',
    expectedConfidence: 72,
    alternativeDiagnoses: ['Pituitary Tumor', 'Diabetes Insipidus', 'Gigantism'],
  },
  {
    id: 'CPX-010',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 29,
    patientGender: 'female',
    chiefComplaint: 'Recurrent miscarriages',
    symptoms: 'Three miscarriages, joint pain, rash on face that worsens in sun, fatigue, positive pregnancy test currently',
    vitals: {
      bloodPressure: '125/80',
      heartRate: 80,
      temperature: 36.8,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Antiphospholipid Syndrome',
    expectedUrgency: 'urgent',
    expectedConfidence: 76,
    alternativeDiagnoses: ['Systemic Lupus Erythematosus', 'Thrombophilia', 'Cervical Insufficiency'],
  },
  {
    id: 'CPX-011',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 67,
    patientGender: 'male',
    chiefComplaint: 'Progressive weakness in legs',
    symptoms: 'Progressive weakness starting in legs, now affecting arms, numbness and tingling, recent respiratory infection',
    vitals: {
      bloodPressure: '115/72',
      heartRate: 88,
      temperature: 37.0,
      oxygenSaturation: 95,
    },
    expectedDiagnosis: 'Guillain-Barré Syndrome',
    expectedUrgency: 'emergency',
    expectedConfidence: 79,
    alternativeDiagnoses: ['Myasthenia Gravis', 'Spinal Cord Compression', 'Polymyositis'],
  },
  {
    id: 'CPX-012',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 44,
    patientGender: 'female',
    chiefComplaint: 'Severe fatigue and darkening skin',
    symptoms: 'Extreme fatigue, weight loss, low blood pressure, darkening of skin especially in creases, salt cravings',
    vitals: {
      bloodPressure: '85/55',
      heartRate: 95,
      temperature: 36.5,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Addison\'s Disease',
    expectedUrgency: 'urgent',
    expectedConfidence: 81,
    alternativeDiagnoses: ['Adrenal Insufficiency', 'Hypothyroidism', 'Chronic Fatigue Syndrome'],
  },
  {
    id: 'CPX-013',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 56,
    patientGender: 'male',
    chiefComplaint: 'Tremor and slow movement',
    symptoms: 'Resting tremor in right hand, slow movements, stiffness, shuffling gait, symptoms progressive over 2 years',
    vitals: {
      bloodPressure: '128/82',
      heartRate: 70,
      temperature: 36.8,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Parkinson\'s Disease',
    expectedUrgency: 'semi-urgent',
    expectedConfidence: 84,
    alternativeDiagnoses: ['Essential Tremor', 'Multiple System Atrophy', 'Drug-Induced Parkinsonism'],
  },
  {
    id: 'CPX-014',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 32,
    patientGender: 'female',
    chiefComplaint: 'Severe pelvic pain',
    symptoms: 'Chronic pelvic pain, painful periods, pain during intercourse, difficulty getting pregnant',
    vitals: {
      bloodPressure: '118/74',
      heartRate: 78,
      temperature: 36.9,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Endometriosis',
    expectedUrgency: 'semi-urgent',
    expectedConfidence: 79,
    alternativeDiagnoses: ['Pelvic Inflammatory Disease', 'Ovarian Cyst', 'Adenomyosis'],
  },
  {
    id: 'CPX-015',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 50,
    patientGender: 'male',
    chiefComplaint: 'Jaundice and abdominal pain',
    symptoms: 'Yellow skin and eyes, dark urine, pale stools, weight loss, upper abdominal pain radiating to back',
    vitals: {
      bloodPressure: '120/78',
      heartRate: 85,
      temperature: 37.2,
      oxygenSaturation: 97,
    },
    expectedDiagnosis: 'Pancreatic Cancer',
    expectedUrgency: 'urgent',
    expectedConfidence: 74,
    alternativeDiagnoses: ['Cholangiocarcinoma', 'Gallstones', 'Hepatitis'],
  },
  {
    id: 'CPX-016',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 39,
    patientGender: 'female',
    chiefComplaint: 'Excessive sweating and palpitations',
    symptoms: 'Episodes of severe sweating, palpitations, headache, very high blood pressure during episodes, anxiety',
    vitals: {
      bloodPressure: '200/120',
      heartRate: 125,
      temperature: 37.5,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Pheochromocytoma',
    expectedUrgency: 'urgent',
    expectedConfidence: 76,
    alternativeDiagnoses: ['Panic Disorder', 'Hyperthyroidism', 'Essential Hypertension'],
  },
  {
    id: 'CPX-017',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 61,
    patientGender: 'male',
    chiefComplaint: 'Bone pain and fatigue',
    symptoms: 'Bone pain especially in back, fatigue, recurrent infections, anemia, elevated calcium',
    vitals: {
      bloodPressure: '125/80',
      heartRate: 88,
      temperature: 37.3,
      oxygenSaturation: 96,
    },
    expectedDiagnosis: 'Multiple Myeloma',
    expectedUrgency: 'urgent',
    expectedConfidence: 77,
    alternativeDiagnoses: ['Bone Metastases', 'Osteoporosis', 'Chronic Infection'],
  },
  {
    id: 'CPX-018',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 47,
    patientGender: 'female',
    chiefComplaint: 'Severe muscle pain and weakness',
    symptoms: 'Severe muscle pain and weakness, especially in shoulders and hips, difficulty rising from chair, elevated muscle enzymes',
    vitals: {
      bloodPressure: '130/85',
      heartRate: 82,
      temperature: 37.0,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Polymyositis',
    expectedUrgency: 'urgent',
    expectedConfidence: 78,
    alternativeDiagnoses: ['Dermatomyositis', 'Statin Myopathy', 'Hypothyroidism'],
  },
  {
    id: 'CPX-019',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 54,
    patientGender: 'male',
    chiefComplaint: 'Swollen lymph nodes and fever',
    symptoms: 'Painless swollen lymph nodes in neck and armpits, fever, night sweats, weight loss, itching',
    vitals: {
      bloodPressure: '122/78',
      heartRate: 90,
      temperature: 38.2,
      oxygenSaturation: 97,
    },
    expectedDiagnosis: 'Hodgkin Lymphoma',
    expectedUrgency: 'urgent',
    expectedConfidence: 80,
    alternativeDiagnoses: ['Non-Hodgkin Lymphoma', 'Tuberculosis', 'HIV/AIDS'],
  },
  {
    id: 'CPX-020',
    category: 'complex',
    difficulty: 'hard',
    patientAge: 42,
    patientGender: 'female',
    chiefComplaint: 'Severe fatigue and cold intolerance',
    symptoms: 'Extreme fatigue, cold intolerance, constipation, dry skin, hair loss, weight gain, depression',
    vitals: {
      bloodPressure: '110/70',
      heartRate: 55,
      temperature: 35.8,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Severe Hypothyroidism',
    expectedUrgency: 'urgent',
    expectedConfidence: 88,
    alternativeDiagnoses: ['Myxedema', 'Depression', 'Chronic Fatigue Syndrome'],
  },

  // ========== PEDIATRIC CASES (10) ==========
  {
    id: 'PED-001',
    category: 'pediatric',
    difficulty: 'medium',
    patientAge: 2,
    patientGender: 'male',
    chiefComplaint: 'Fever and difficulty breathing',
    symptoms: 'High fever for 2 days, wheezing, rapid breathing, cough, runny nose, decreased feeding',
    vitals: {
      bloodPressure: '90/60',
      heartRate: 145,
      temperature: 39.0,
      oxygenSaturation: 91,
      respiratoryRate: 50,
    },
    expectedDiagnosis: 'Bronchiolitis',
    expectedUrgency: 'urgent',
    expectedConfidence: 87,
    alternativeDiagnoses: ['Pneumonia', 'Asthma', 'Viral Upper Respiratory Infection'],
  },
  {
    id: 'PED-002',
    category: 'pediatric',
    difficulty: 'easy',
    patientAge: 6,
    patientGender: 'female',
    chiefComplaint: 'Ear pain and fever',
    symptoms: 'Right ear pain, pulling at ear, fever, irritable, recent cold',
    vitals: {
      bloodPressure: '95/65',
      heartRate: 120,
      temperature: 38.5,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Acute Otitis Media',
    expectedUrgency: 'routine',
    expectedConfidence: 91,
    alternativeDiagnoses: ['Otitis Externa', 'Upper Respiratory Infection', 'Mastoiditis'],
  },
  {
    id: 'PED-003',
    category: 'pediatric',
    difficulty: 'medium',
    patientAge: 4,
    patientGender: 'male',
    chiefComplaint: 'Barking cough',
    symptoms: 'Barking cough, hoarse voice, stridor when breathing, worse at night, recent cold',
    vitals: {
      bloodPressure: '92/62',
      heartRate: 130,
      temperature: 37.8,
      oxygenSaturation: 95,
      respiratoryRate: 35,
    },
    expectedDiagnosis: 'Croup',
    expectedUrgency: 'urgent',
    expectedConfidence: 89,
    alternativeDiagnoses: ['Epiglottitis', 'Foreign Body Aspiration', 'Asthma'],
  },
  {
    id: 'PED-004',
    category: 'pediatric',
    difficulty: 'easy',
    patientAge: 8,
    patientGender: 'female',
    chiefComplaint: 'Rash and fever',
    symptoms: 'Red rash that started on face and spread to body, fever for 3 days, cough, runny nose, red eyes',
    vitals: {
      bloodPressure: '98/65',
      heartRate: 110,
      temperature: 38.8,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Measles',
    expectedUrgency: 'urgent',
    expectedConfidence: 85,
    alternativeDiagnoses: ['Rubella', 'Roseola', 'Scarlet Fever'],
  },
  {
    id: 'PED-005',
    category: 'pediatric',
    difficulty: 'medium',
    patientAge: 5,
    patientGender: 'male',
    chiefComplaint: 'Abdominal pain and vomiting',
    symptoms: 'Severe abdominal pain around belly button, vomiting, no diarrhea, pain comes in waves, crying inconsolably',
    vitals: {
      bloodPressure: '85/55',
      heartRate: 135,
      temperature: 37.2,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Intussusception',
    expectedUrgency: 'emergency',
    expectedConfidence: 82,
    alternativeDiagnoses: ['Gastroenteritis', 'Appendicitis', 'Constipation'],
  },
  {
    id: 'PED-006',
    category: 'pediatric',
    difficulty: 'easy',
    patientAge: 10,
    patientGender: 'female',
    chiefComplaint: 'Sore throat and rash',
    symptoms: 'Severe sore throat, fever, sandpaper-like rash on body, strawberry tongue, swollen neck glands',
    vitals: {
      bloodPressure: '100/68',
      heartRate: 115,
      temperature: 39.0,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Scarlet Fever',
    expectedUrgency: 'routine',
    expectedConfidence: 88,
    alternativeDiagnoses: ['Strep Throat', 'Viral Pharyngitis', 'Kawasaki Disease'],
  },
  {
    id: 'PED-007',
    category: 'pediatric',
    difficulty: 'hard',
    patientAge: 3,
    patientGender: 'male',
    chiefComplaint: 'High fever and red eyes',
    symptoms: 'High fever for 5 days, red eyes, red cracked lips, swollen hands and feet, rash, irritable',
    vitals: {
      bloodPressure: '92/60',
      heartRate: 140,
      temperature: 39.5,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Kawasaki Disease',
    expectedUrgency: 'emergency',
    expectedConfidence: 80,
    alternativeDiagnoses: ['Scarlet Fever', 'Viral Exanthem', 'Stevens-Johnson Syndrome'],
  },
  {
    id: 'PED-008',
    category: 'pediatric',
    difficulty: 'medium',
    patientAge: 1,
    patientGender: 'female',
    chiefComplaint: 'Watery diarrhea and vomiting',
    symptoms: 'Watery diarrhea multiple times, vomiting, decreased wet diapers, lethargic, dry mouth',
    vitals: {
      bloodPressure: '75/50',
      heartRate: 155,
      temperature: 37.8,
      oxygenSaturation: 97,
    },
    expectedDiagnosis: 'Severe Dehydration from Gastroenteritis',
    expectedUrgency: 'urgent',
    expectedConfidence: 90,
    alternativeDiagnoses: ['Rotavirus', 'Bacterial Gastroenteritis', 'Food Intolerance'],
  },
  {
    id: 'PED-009',
    category: 'pediatric',
    difficulty: 'easy',
    patientAge: 7,
    patientGender: 'male',
    chiefComplaint: 'Itchy rash',
    symptoms: 'Itchy rash with small blisters, started on trunk now spreading, low fever, some blisters crusted',
    vitals: {
      bloodPressure: '98/64',
      heartRate: 105,
      temperature: 37.5,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Chickenpox',
    expectedUrgency: 'routine',
    expectedConfidence: 92,
    alternativeDiagnoses: ['Impetigo', 'Hand-Foot-Mouth Disease', 'Insect Bites'],
  },
  {
    id: 'PED-010',
    category: 'pediatric',
    difficulty: 'medium',
    patientAge: 9,
    patientGender: 'female',
    chiefComplaint: 'Swollen cheeks',
    symptoms: 'Swollen cheeks on both sides, pain when chewing, fever, headache, no vaccination history',
    vitals: {
      bloodPressure: '102/68',
      heartRate: 100,
      temperature: 38.3,
      oxygenSaturation: 99,
    },
    expectedDiagnosis: 'Mumps',
    expectedUrgency: 'routine',
    expectedConfidence: 87,
    alternativeDiagnoses: ['Parotitis', 'Lymphadenitis', 'Dental Abscess'],
  },

  // ========== GERIATRIC CASES (10) ==========
  {
    id: 'GER-001',
    category: 'geriatric',
    difficulty: 'medium',
    patientAge: 78,
    patientGender: 'female',
    chiefComplaint: 'Fall and hip pain',
    symptoms: 'Fell at home, severe hip pain, unable to bear weight, leg appears shortened and rotated outward',
    vitals: {
      bloodPressure: '145/88',
      heartRate: 95,
      temperature: 36.8,
      oxygenSaturation: 96,
    },
    expectedDiagnosis: 'Hip Fracture',
    expectedUrgency: 'emergency',
    expectedConfidence: 93,
    alternativeDiagnoses: ['Hip Dislocation', 'Femoral Fracture', 'Pelvic Fracture'],
  },
  {
    id: 'GER-002',
    category: 'geriatric',
    difficulty: 'hard',
    patientAge: 82,
    patientGender: 'male',
    chiefComplaint: 'Confusion and fever',
    symptoms: 'Sudden confusion, fever, burning urination, foul-smelling urine, history of enlarged prostate',
    vitals: {
      bloodPressure: '100/65',
      heartRate: 105,
      temperature: 38.8,
      oxygenSaturation: 94,
    },
    expectedDiagnosis: 'Urosepsis',
    expectedUrgency: 'emergency',
    expectedConfidence: 88,
    alternativeDiagnoses: ['Urinary Tract Infection', 'Delirium', 'Pneumonia'],
  },
  {
    id: 'GER-003',
    category: 'geriatric',
    difficulty: 'medium',
    patientAge: 75,
    patientGender: 'female',
    chiefComplaint: 'Dizziness when standing',
    symptoms: 'Dizziness when standing up, nearly fainted twice, on multiple blood pressure medications, worse in morning',
    vitals: {
      bloodPressure: '160/90 lying, 110/70 standing',
      heartRate: 72,
      temperature: 36.7,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Orthostatic Hypotension',
    expectedUrgency: 'semi-urgent',
    expectedConfidence: 89,
    alternativeDiagnoses: ['Dehydration', 'Cardiac Arrhythmia', 'Medication Side Effect'],
  },
  {
    id: 'GER-004',
    category: 'geriatric',
    difficulty: 'hard',
    patientAge: 80,
    patientGender: 'male',
    chiefComplaint: 'Shortness of breath and swollen legs',
    symptoms: 'Progressive shortness of breath, swollen ankles, sleeping sitting up, cough with pink frothy sputum',
    vitals: {
      bloodPressure: '150/95',
      heartRate: 110,
      temperature: 36.9,
      oxygenSaturation: 88,
      respiratoryRate: 28,
    },
    expectedDiagnosis: 'Acute Decompensated Heart Failure',
    expectedUrgency: 'emergency',
    expectedConfidence: 91,
    alternativeDiagnoses: ['Pneumonia', 'COPD Exacerbation', 'Pulmonary Edema'],
  },
  {
    id: 'GER-005',
    category: 'geriatric',
    difficulty: 'medium',
    patientAge: 73,
    patientGender: 'female',
    chiefComplaint: 'Black tarry stools',
    symptoms: 'Black tarry stools for 2 days, feeling weak and dizzy, pale, takes aspirin and ibuprofen daily for arthritis',
    vitals: {
      bloodPressure: '95/60',
      heartRate: 115,
      temperature: 36.5,
      oxygenSaturation: 95,
    },
    expectedDiagnosis: 'Upper GI Bleeding from NSAID Use',
    expectedUrgency: 'emergency',
    expectedConfidence: 90,
    alternativeDiagnoses: ['Peptic Ulcer', 'Gastritis', 'Esophageal Varices'],
  },
  {
    id: 'GER-006',
    category: 'geriatric',
    difficulty: 'hard',
    patientAge: 85,
    patientGender: 'male',
    chiefComplaint: 'Sudden confusion',
    symptoms: 'Sudden onset confusion this morning, normal yesterday, urinary incontinence, difficulty walking, no fever',
    vitals: {
      bloodPressure: '165/95',
      heartRate: 88,
      temperature: 36.8,
      oxygenSaturation: 96,
    },
    expectedDiagnosis: 'Normal Pressure Hydrocephalus',
    expectedUrgency: 'urgent',
    expectedConfidence: 75,
    alternativeDiagnoses: ['Stroke', 'Urinary Tract Infection', 'Dementia'],
  },
  {
    id: 'GER-007',
    category: 'geriatric',
    difficulty: 'medium',
    patientAge: 76,
    patientGender: 'female',
    chiefComplaint: 'Severe back pain',
    symptoms: 'Sudden severe back pain after minor fall, history of osteoporosis, tenderness over spine',
    vitals: {
      bloodPressure: '140/85',
      heartRate: 88,
      temperature: 36.7,
      oxygenSaturation: 97,
    },
    expectedDiagnosis: 'Vertebral Compression Fracture',
    expectedUrgency: 'urgent',
    expectedConfidence: 87,
    alternativeDiagnoses: ['Muscle Strain', 'Spinal Stenosis', 'Osteoarthritis'],
  },
  {
    id: 'GER-008',
    category: 'geriatric',
    difficulty: 'hard',
    patientAge: 79,
    patientGender: 'male',
    chiefComplaint: 'Chest pain atypical presentation',
    symptoms: 'Vague chest discomfort, nausea, fatigue, no classic chest pain, diabetic, symptoms for 2 hours',
    vitals: {
      bloodPressure: '110/70',
      heartRate: 95,
      temperature: 36.8,
      oxygenSaturation: 93,
    },
    expectedDiagnosis: 'Atypical Myocardial Infarction',
    expectedUrgency: 'emergency',
    expectedConfidence: 82,
    alternativeDiagnoses: ['GERD', 'Anxiety', 'Costochondritis'],
  },
  {
    id: 'GER-009',
    category: 'geriatric',
    difficulty: 'medium',
    patientAge: 81,
    patientGender: 'female',
    chiefComplaint: 'Difficulty swallowing',
    symptoms: 'Progressive difficulty swallowing, weight loss, food getting stuck, regurgitation, cough after eating',
    vitals: {
      bloodPressure: '125/78',
      heartRate: 76,
      temperature: 36.8,
      oxygenSaturation: 97,
    },
    expectedDiagnosis: 'Esophageal Cancer',
    expectedUrgency: 'urgent',
    expectedConfidence: 78,
    alternativeDiagnoses: ['Achalasia', 'GERD', 'Esophageal Stricture'],
  },
  {
    id: 'GER-010',
    category: 'geriatric',
    difficulty: 'medium',
    patientAge: 74,
    patientGender: 'male',
    chiefComplaint: 'Urinary retention',
    symptoms: 'Unable to urinate for 12 hours, severe lower abdominal pain, history of enlarged prostate',
    vitals: {
      bloodPressure: '155/90',
      heartRate: 95,
      temperature: 37.0,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Acute Urinary Retention',
    expectedUrgency: 'emergency',
    expectedConfidence: 92,
    alternativeDiagnoses: ['Benign Prostatic Hyperplasia', 'Prostate Cancer', 'Bladder Outlet Obstruction'],
  },

  // ========== IRAQI-SPECIFIC CASES (10) ==========
  {
    id: 'IRQ-001',
    category: 'iraqi-specific',
    difficulty: 'medium',
    patientAge: 35,
    patientGender: 'male',
    chiefComplaint: 'Chronic fever and weight loss',
    symptoms: 'Persistent fever for 3 weeks, night sweats, weight loss, cough, lived in rural area, exposure to farm animals',
    vitals: {
      bloodPressure: '115/75',
      heartRate: 92,
      temperature: 38.5,
      oxygenSaturation: 96,
    },
    expectedDiagnosis: 'Brucellosis',
    expectedUrgency: 'urgent',
    expectedConfidence: 83,
    alternativeDiagnoses: ['Tuberculosis', 'Typhoid Fever', 'Lymphoma'],
  },
  {
    id: 'IRQ-002',
    category: 'iraqi-specific',
    difficulty: 'hard',
    patientAge: 28,
    patientGender: 'female',
    chiefComplaint: 'Skin lesion and fever',
    symptoms: 'Painless skin ulcer on face, started as papule, fever, enlarged spleen, recent travel to southern Iraq',
    vitals: {
      bloodPressure: '118/72',
      heartRate: 88,
      temperature: 38.0,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Cutaneous Leishmaniasis',
    expectedUrgency: 'semi-urgent',
    expectedConfidence: 85,
    alternativeDiagnoses: ['Bacterial Skin Infection', 'Fungal Infection', 'Skin Cancer'],
  },
  {
    id: 'IRQ-003',
    category: 'iraqi-specific',
    difficulty: 'medium',
    patientAge: 42,
    patientGender: 'male',
    chiefComplaint: 'High fever and headache',
    symptoms: 'High fever, severe headache, abdominal pain, constipation, rose-colored spots on chest, contaminated water exposure',
    vitals: {
      bloodPressure: '110/70',
      heartRate: 85,
      temperature: 39.5,
      oxygenSaturation: 97,
    },
    expectedDiagnosis: 'Typhoid Fever',
    expectedUrgency: 'urgent',
    expectedConfidence: 87,
    alternativeDiagnoses: ['Malaria', 'Dengue', 'Brucellosis'],
  },
  {
    id: 'IRQ-004',
    category: 'iraqi-specific',
    difficulty: 'hard',
    patientAge: 50,
    patientGender: 'male',
    chiefComplaint: 'Abdominal mass',
    symptoms: 'Slowly growing abdominal mass, no pain, history of contact with dogs, lived in rural area',
    vitals: {
      bloodPressure: '125/80',
      heartRate: 76,
      temperature: 36.9,
      oxygenSaturation: 98,
    },
    expectedDiagnosis: 'Hydatid Cyst Disease',
    expectedUrgency: 'semi-urgent',
    expectedConfidence: 80,
    alternativeDiagnoses: ['Liver Abscess', 'Liver Cancer', 'Polycystic Liver Disease'],
  },
  {
    id: 'IRQ-005',
    category: 'iraqi-specific',
    difficulty: 'medium',
    patientAge: 32,
    patientGender: 'female',
    chiefComplaint: 'High fever and joint pain',
    symptoms: 'Sudden high fever, severe joint and muscle pain, headache, rash, recent mosquito bites',
    vitals: {
      bloodPressure: '110/70',
      heartRate: 100,
      temperature: 39.8,
      oxygenSaturation: 97,
    },
    expectedDiagnosis: 'Dengue Fever',
    expectedUrgency: 'urgent',
    expectedConfidence: 86,
    alternativeDiagnoses: ['Chikungunya', 'Malaria', 'Viral Infection'],
  },
  {
    id: 'IRQ-006',
    category: 'iraqi-specific',
    difficulty: 'hard',
    patientAge: 45,
    patientGender: 'male',
    chiefComplaint: 'Chronic cough and fever',
    symptoms: 'Persistent cough for 2 months, coughing up blood, night sweats, weight loss, chest pain, known TB contact',
    vitals: {
      bloodPressure: '120/75',
      heartRate: 95,
      temperature: 38.2,
      oxygenSaturation: 92,
    },
    expectedDiagnosis: 'Pulmonary Tuberculosis',
    expectedUrgency: 'urgent',
    expectedConfidence: 91,
    alternativeDiagnoses: ['Lung Cancer', 'Chronic Bronchitis', 'Pneumonia'],
  },
  {
    id: 'IRQ-007',
    category: 'iraqi-specific',
    difficulty: 'medium',
    patientAge: 38,
    patientGender: 'female',
    chiefComplaint: 'Cyclic fever',
    symptoms: 'Fever every 48 hours, chills, sweating, headache, recent travel to marshlands, no mosquito protection',
    vitals: {
      bloodPressure: '115/72',
      heartRate: 105,
      temperature: 40.0,
      oxygenSaturation: 96,
    },
    expectedDiagnosis: 'Malaria',
    expectedUrgency: 'urgent',
    expectedConfidence: 88,
    alternativeDiagnoses: ['Dengue', 'Typhoid', 'Viral Infection'],
  },
  {
    id: 'IRQ-008',
    category: 'iraqi-specific',
    difficulty: 'hard',
    patientAge: 55,
    patientGender: 'male',
    chiefComplaint: 'Liver enlargement and ascites',
    symptoms: 'Abdominal swelling, enlarged liver, history of schistosomiasis, contact with contaminated water',
    vitals: {
      bloodPressure: '110/70',
      heartRate: 82,
      temperature: 37.2,
      oxygenSaturation: 97,
    },
    expectedDiagnosis: 'Hepatic Schistosomiasis',
    expectedUrgency: 'semi-urgent',
    expectedConfidence: 79,
    alternativeDiagnoses: ['Liver Cirrhosis', 'Hepatitis', 'Liver Cancer'],
  },
  {
    id: 'IRQ-009',
    category: 'iraqi-specific',
    difficulty: 'medium',
    patientAge: 29,
    patientGender: 'male',
    chiefComplaint: 'Severe diarrhea',
    symptoms: 'Severe watery diarrhea, vomiting, severe dehydration, recent consumption of contaminated water',
    vitals: {
      bloodPressure: '85/55',
      heartRate: 125,
      temperature: 37.0,
      oxygenSaturation: 96,
    },
    expectedDiagnosis: 'Cholera',
    expectedUrgency: 'emergency',
    expectedConfidence: 84,
    alternativeDiagnoses: ['Severe Gastroenteritis', 'Food Poisoning', 'Rotavirus'],
  },
  {
    id: 'IRQ-010',
    category: 'iraqi-specific',
    difficulty: 'hard',
    patientAge: 48,
    patientGender: 'female',
    chiefComplaint: 'Chronic anemia',
    symptoms: 'Chronic fatigue, pale, blood in stool, abdominal pain, history of living near Tigris River',
    vitals: {
      bloodPressure: '105/68',
      heartRate: 98,
      temperature: 36.8,
      oxygenSaturation: 94,
    },
    expectedDiagnosis: 'Intestinal Schistosomiasis',
    expectedUrgency: 'semi-urgent',
    expectedConfidence: 77,
    alternativeDiagnoses: ['Inflammatory Bowel Disease', 'Colorectal Cancer', 'Hookworm Infection'],
  },
];
